"""
Operational Modes Module
==========================
Forensic and Popperian modes for covenant-driven operations

File Hash (SHA-256): [AUTOGENERATED]
"""

class OperationalMode:
    """Base class for operational modes."""
    
    def __init__(self, name, description, allowed, prohibited):
        self.name = name
        self.description = description
        self.allowed_operations = allowed
        self.prohibited_operations = prohibited
    
    def is_allowed(self, operation):
        """Check if operation is allowed in this mode."""
        return operation in self.allowed_operations and operation not in self.prohibited_operations


# FORENSIC MODE: Bytes and hashes only
FORENSIC = OperationalMode(
    name="FORENSIC",
    description="Bytes and hashes only. No psychology.",
    allowed=[
        "hash_verification",
        "log_analysis",
        "artifact_comparison",
        "chain_of_custody_tracking"
    ],
    prohibited=[
        "emotion_labeling",
        "intent_inference",
        "psychological_assessment",
        "motivation_analysis"
    ]
)

# POPPERIAN MODE: Falsification-first
POPPERIAN = OperationalMode(
    name="POPPERIAN",
    description="Falsification-first. No interpretation.",
    allowed=[
        "hypothesis_testing",
        "counterexample_search",
        "falsification_attempts",
        "evidence_based_refutation"
    ],
    prohibited=[
        "interpretive_analysis",
        "hermeneutic_reading",
        "narrative_construction",
        "speculative_explanation"
    ]
)

MODES = {
    "forensic": FORENSIC,
    "popperian": POPPERIAN
}
